### ISSUE TITLE
Can you write a compress program?Thank you

### ISSUE THREAD

**Issue by Zacior** [MaKiPL/JAP_JustDance_JDCZlib_Decompressor#1]
I use your decompress program and get the setting file,I changed this file but I can not compress to let game read.Please help me ,the code that I uploaded maybe can help you. Thank you and forgive my poor English.
[JDCZlibWrapper.cs.txt](https://github.com/MaKiPL/JAP_JustDance_JDCZlib_Decompressor/files/921703/JDCZlibWrapper.cs.txt)

**Comment by MaKiPL** [comment]
Yes, sure. I do remember about it. I'll take care of it ASAP.

**Comment by Zacior** [comment]
This program is useful，Thank you ! ！！
